services:
  - type: web
    name: sih-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: CLOUD_NAME
        value: dsf0yp2hr
      - key: CLOUD_API_KEY
        value: 563713949862699
      - key: CLOUD_API_SECRET
        value: d_HSX5dQCyDnZaCWltF0SNyDVwk
